-- AlterTable
ALTER TABLE "tvmed_mipres" RENAME CONSTRAINT "tv_med_pkey" TO "tvmed_mipres_pkey";

-- CreateTable
CREATE TABLE "measurement_units" (
    "code" INTEGER NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "measurement_units_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "pharmaceutical_forms" (
    "code" TEXT NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "pharmaceutical_forms_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "tvmed_evento" (
    "id" SERIAL NOT NULL,
    "cum" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "value" INTEGER NOT NULL,
    "concentration" TEXT NOT NULL,
    "presentation" TEXT NOT NULL,
    "administration_route" TEXT NOT NULL,
    "short_name" TEXT NOT NULL,
    "measurement_unit" INTEGER NOT NULL,
    "pharmaceutical_form" TEXT NOT NULL,
    "dispensing_unit" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tvmed_evento_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tvmed_evento_cum_idx" ON "tvmed_evento"("cum");

-- AddForeignKey
ALTER TABLE "tvmed_evento" ADD CONSTRAINT "tvmed_evento_measurement_unit_fkey" FOREIGN KEY ("measurement_unit") REFERENCES "measurement_units"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tvmed_evento" ADD CONSTRAINT "tvmed_evento_dispensing_unit_fkey" FOREIGN KEY ("dispensing_unit") REFERENCES "measurement_units"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tvmed_evento" ADD CONSTRAINT "tvmed_evento_pharmaceutical_form_fkey" FOREIGN KEY ("pharmaceutical_form") REFERENCES "pharmaceutical_forms"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Seed measurement_units (catálogo de referencia)
INSERT INTO "measurement_units" ("code","description") VALUES
(1,'AMPOLLA'),(2,'APLICADOR'),(3,'BOLSA'),(4,'BARRA'),(5,'PERLA'),(6,'BLISTER'),(7,'ENVASE BLISTER'),(8,'BLOQUE'),(9,'BOLO'),(10,'ENVASE'),
(11,'CAJA'),(12,'LATA'),(13,'FRASCO'),(14,'CAPSULA'),(15,'CARTON'),(16,'CARTUCHO'),(17,'ESTUCHE'),(18,'PELICULA DE PVC TRANSPARENTE DE COLORES'),(19,'UNIDADES CLINICAS'),(20,'RECUBRIMIENTO'),
(21,'CONTENEDOR'),(22,'RECUENTO'),(23,'COPA'),(24,'CILINDRO'),(25,'VASOS DEWAR'),(26,'DIAL PACK'),(27,'DISCO'),(28,'DOSIS EN ENVASE'),(29,'GOTAS'),(30,'TAMBOR - BOMBO'),
(31,'PELICULA'),(32,'GENERADOR'),(33,'GLOBULO'),(34,'DILUCION HOMEOPATICA'),(35,'IMPLANTE'),(36,'INHALACION'),(37,'INHALADOR'),(38,'INHALADOR, RECARGA'),(39,'INSERTO'),(40,'FRASCO'),
(41,'JARRA'),(42,'UNIDAD INHIBIDORA DE CALICREINA'),(43,'KIT'),(44,'PASTILLA'),(45,'EMBALAJE'),(46,'PAQUETE'),(47,'BALDE'),(48,'PARTES'),(49,'PARCHE'),(50,'PILDORA (PELLET)'),
(51,'PIEZA'),(53,'UNIDADES DE PRESION'),(54,'ANILLO'),(55,'SATURADO'),(56,'CUCHARA MEDIDORA'),(57,'ESPONJA'),(58,'ATOMIZADOR (SPRAY)'),(59,'CENTIMETRO CUADRADO'),(61,'TIRA'),(63,'SUPOSITORIO'),
(64,'HISOPO'),(65,'JERINGA'),(66,'TABLETA'),(67,'TABMINDER'),(68,'TAMPON'),(69,'TANQUE'),(70,'PRUEBA'),(71,'BANDEJA'),(72,'TROCHE'),(73,'TUBO'),
(74,'UNIDADES'),(75,'VIAL'),(76,'OBLEA'),(77,'TERMO'),(78,'SOBRE'),(79,'PLUMA'),(80,'LITRO'),(81,'OVULO')
ON CONFLICT ("code") DO NOTHING;

-- Seed pharmaceutical_forms (catálogo de referencia)
INSERT INTO "pharmaceutical_forms" ("code","description") VALUES
('C28944','CREMA'),('C29167','LOCION'),('C29269','ENJUAGUE'),('C42887','AEROSOL'),('C42902','CAPSULA DE LIBERACION RETARDADA'),
('C42905','TABLETAS DE LIBERACION RETARDADA'),('C42909','GRANULOS EFERVESCENTES'),('C42912','ELIXIR'),('C42914','EMULSION INYECTABLE'),('C42916','CAPSULA DE LIBERACION PROLONGADA'),
('C42927','TABLETAS DE LIBERACION PROLONGADA'),('C42932','CINTA ADHESIVA / PELICULA'),('C42933','GAS'),('C42938','GRANULOS CONVENCIONALES'),('C42941','GOMA'),
('C42942','IMPLANTE'),('C42948','GELES y JALEAS'),('C42953','LIQUIDO (Diferentes a soluciones)'),('C42966','UNGÜENTO'),('C42967','PASTA'),
('C42968','SISTEMAS TRANSDERMICOS'),('C42969','PELLETS'),('C42983','JABONES Y CHAMPU'),('C42989','ESPRAY'),('C42993','SUPOSITORIO / OVULO'),
('C42994','SUSPENSION'),('C42996','JARABE'),('C43000','TINTURA'),('C47913','EMPLASTO'),('C47914','TIRA'),
('C47915','SISTEMAS INTRAUTERINOS'),('C64898','ESPUMA'),('C64904','CAPSULA CUBIERTA DURA'),('C64909','CAPSULA BLANDA'),('C69031','SISTEMAS OCULARES'),
('C91199','SISTEMAS DE ANILLOS VAGINALES'),('C91200','SISTEMAS'),('COLFF001','TABLETAS DE LIBERACION NO MODIFICADA'),('COLFF002','POLVOS PARA NO RECONSTITUIR'),('COLFF003','POLVOS PARA RECONSTITUIR'),
('COLFF004','OTRAS SOLUCIONES'),('COLFF005','AS EMULSIONES'),('COLFF006','CAPSULAS DE LIBERACION NO MODIFICADA'),('COLFF007','CAPSULAS DE LIBERACION MODIFICADA'),('COLFF008','TABLETAS DE LIBERACION MODIFICADA'),
('COLFF009','GRANULOS DE LIBERACION NO MODIFICADA'),('COLFF010','GRANULOS DE LIBERACION MODIFICADA')
ON CONFLICT ("code") DO NOTHING;
