-- Catálogo de unidades de medida científicas (mg, ml, UI…): código + símbolo + descripción.
CREATE TABLE "scientific_units" (
    "code" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    CONSTRAINT "scientific_units_pkey" PRIMARY KEY ("code")
);

-- Seed (274 filas: códigos 0..257 + 9000..9015).
INSERT INTO "scientific_units" ("code","name","description") VALUES
(0,'',''),
(1,'EID50','dosis infecciosa de embrión 50'),
(2,'EID50/dosis','dosis infecciosa de embrión 50/dosis'),
(3,'AU/ml','unidades de alergia/mililitro'),
(4,'A','amperio'),
(5,'AgU','unidad(es) de antígeno'),
(6,'AgU/ml','unidad(es) de antígeno/mililitro'),
(7,'ATU','unidades de antitrombina'),
(8,'anti-Xa IU','unidades internacionales de actividad anti-Xa'),
(9,'anti-Xa IU/ml','unidades internacionales de actividad anti-Xa/mililitro'),
(10,'Bq','bequerel(ios)'),
(11,'Bq/g','bequerel(ios)/gramo'),
(12,'Bq/kg','bequerel(ios)/kilogramo'),
(13,'Bq/l','bequerel(ios)/litro'),
(14,'Bq/µg','bequerel(ios)/microgramo'),
(15,'Bq/µl','bequerel(ios)/microlitro'),
(16,'Bq/mg','bequerel(ios)/miligramo'),
(17,'Bq/ml','bequerel(ios)/mililitro'),
(18,'billon CFU','billon de unidades formadoras de colonia'),
(19,'billon CFU/g','billon de unidades formadoras de colonia/gramo'),
(20,'billon CFU/ml','billon de unidades formadoras de colonia/mililitro'),
(21,'billon de organismos','billon de organismos'),
(22,'billon de organismos/g','billon de organismos/gramo'),
(23,'billon de organismos/mg','billon de organismos/miligramo'),
(24,'biorganismos/ml','billon de organismos/mililitro'),
(25,'cd','candela'),
(26,'CCID50','dosis infecciosa cultivo celular 50'),
(27,'CCID50/dosis','dosis infecciosa cultivo celular 50/dosis'),
(28,'°C','temperatura en Celsius'),
(29,'CFU/g','unidades formadoras de colonias/gramo'),
(30,'CFU/ml','nidades formadoras de colonias/mililitro'),
(31,'Co','culombio'),
(32,'m3','metro cúbico'),
(33,'Ci','curio(s)'),
(34,'Ci/g','curie(s)/gramo'),
(35,'Ci/kg','curie(s)/kilogramo'),
(36,'Ci/litro','curie(s)/litro'),
(37,'Ci/µg','curie(s)/microgramo'),
(38,'Ci/µl','curie(s)/microlitro'),
(39,'Ci/mg','curie(s)/miligramo'),
(40,'Ci/ml','curie(s)/mililitro'),
(41,'DAgU','unidad(es) de Antigeno D'),
(42,'DAgU/ml','unidad(es) de Antigeno D/mililitro'),
(43,'d','dia'),
(44,'°','grado'),
(45,'DF','forma de dosificación'),
(46,'Gtt','gota(s)'),
(47,'unidades ELISA','unidad de ensayo inmunoenzimático'),
(48,'unidades ELISA/dosis','unidad de ensayo inmunoenzimático/dosis'),
(49,'unidades ELISA/ml','unidad de ensayo inmunoenzimático/mililitro'),
(50,'F','faradio'),
(51,'FAI50','ensayo fluorescente dosis infecciosa 50'),
(52,'FAI50/dosis','ensayo fluorescente dosis infecciosa 50/dosis'),
(53,'GBq','gigabecquerel(ios)'),
(54,'GBq/g','grel/gramo'),
(55,'GBq/kg','gigabecquerel/kilogramo'),
(56,'GBq/l','gigabecquerel/litro'),
(57,'GBq/µg','gigabecquerel/microgramo'),
(58,'GBq/µl','gigabecquerel/microlitro'),
(59,'GBq/mg','gigabecquerel/miligramo'),
(60,'GBq/ml','gigabecquerel/mililitro'),
(61,'g (titre)','gramo (titre)'),
(62,'g','gramo(s)'),
(63,'g/m3','gramo/metro cúbico'),
(64,'g/l','gramo/litro'),
(65,'g/ml','gramo/mililitro'),
(66,'g/m2','gramo/metro cuadrado'),
(67,'Gy','gray'),
(68,'H','henrio'),
(69,'Hz','hertz'),
(70,'h','hora'),
(71,'IOU','unidad(es) internacional(es) de opacidad'),
(72,'UI','unidad(es) internacional(es)'),
(73,'UI/g','unidad(es) internacional(es)/gramo'),
(74,'UI/kg','unidad(es) internacional(es)/kilogramo'),
(75,'UI/l','unidad(es) internacional(es)/litro'),
(76,'UI/mg','unidad(es) internacional(es)/miligramo'),
(77,'UI/ml','unidad(es) internacional(es)/mililitro'),
(78,'J','julio'),
(79,'KIU/ml','unidad calicreína inactivador/mililitro'),
(80,'kat','katal'),
(81,'K','kelvin'),
(82,'kUI','unidad internacional de kilo'),
(83,'unidades Kusp','unidad de la Farmacopea de los Estados Unidos de kilo'),
(84,'unidades k','unidades kilo'),
(85,'kBq','kilobecquerel(ios)'),
(86,'kBq/g','kilobecquerel(ios)/gramo'),
(87,'kBq/kg','kilobecquerel(ios)ogramo'),
(88,'kBq/l','kilobecquerel(ios)/litro'),
(89,'kBq/µg','kilobecquerel(ios)/microgramo'),
(90,'kBq/µl','kilobecquerel(ios)/microlitro'),
(91,'kBq/mg','kilobecquerel(ios)/miligramo'),
(92,'kBq/ml','kilobecquerel(ios)/mililitro'),
(93,'kg','kilogramo(s)'),
(94,'kg/m3','kilogramo(s)/metro cúbico'),
(95,'kg/l','kilogramo(s)/litro'),
(96,'kg/m2','kilogramo(s)/metro cuadrado'),
(97,'LacU','unidades de lactasa'),
(98,'LfU','unidades de floculación (lime flocculation unit(s))'),
(99,'LfU/ml','unidades de floculación (lime flocculation unit(s))/mililitro'),
(100,'l','litro(s)'),
(101,'log10 EID50','log 10 50% dosis infecciosa de embrión'),
(102,'log10 EID51/dosis','log 10 50% dosis infecciosa de embrión/dosis'),
(103,'log10 CCID50','log10 dosis infecciosa cultivo celular 50'),
(104,'log10 CCID50/dosis','log10 dosis infecciosa de cultivo celular 50/dosis'),
(105,'log10 unidades ELISA','log10 unidad de ensayo inmunoenzimático'),
(106,'log10 unidades ELISA/dosis','log10 unidad de ensayo inmunoenzimático/dosis'),
(107,'log10 FAI50','log10 ensayo fluorescente dosis infecciosa del 50%'),
(108,'log10 FAI50/dosis','log10 ensayo fluorescente dosis infel 50%/dosis'),
(109,'log10 PFU','log10 unidad(es) formadoras de placa'),
(110,'log10 PFU/dosis','log10 unidad(es) formadoras de placa/dosis'),
(111,'log10 TCID50','log10 dosis infecciosa de cultivo tisular 50%'),
(112,'log10 TCID50/dosis','log10 dosis infecciosa de cultivo tisular 50%/dosis'),
(113,'log10/ml','log10/ml'),
(114,'LU','unidades de loomis'),
(115,'LU/g','unidades de loomis/gramo'),
(116,'LU/ml','unidades de loomis/mililitro'),
(117,'lm','lumen'),
(118,'lx','lux'),
(119,'unidades MUSP','"""mega; unidad de la Farmacopea de los Estados Unidos"""'),
(120,'MBq','megabecquerel(ios)'),
(121,'MBq/g','megabecquerel(ios)/gramo'),
(122,'MBq/kg','megabecquerel(ios)/kilogramo'),
(123,'MBq/l','megabecquerel(ios)/litro'),
(124,'MBq/µg','megabecquerel(ios)/microgramo'),
(125,'MBq/µl','megabecquerel(ios)/microlitro'),
(126,'MBq/mg','megabecquerel(ios)/miligramo'),
(127,'MBq/ml','megabecquerel(ios)/mililitro'),
(128,'m','metro'),
(129,'µCi','microcurio(s)'),
(130,'µCi/g','microcurio(s)/gramo'),
(131,'µCi/kg','microcurio(s)/kilogramo'),
(132,'µCi/l','microcurio(s)/litro'),
(133,'µCi/µg','microcurio(s)/microgramo'),
(134,'µCi/µl','microcurio(s)/microlitro'),
(135,'µCi/mg','microcurio(s)/miligramo'),
(136,'µCi/ml','microcurio(s)/mililitro'),
(137,'µg','microgramo(s)'),
(138,'µg/m3','microgramo(s)/metro cúbico'),
(139,'µg/kg','microgramo(s)/kilogramo'),
(140,'µg/l','microgramo(s)/litro'),
(141,'µg/µl','microgramo(s)/microlitro'),
(142,'µg/ml','microgramo(s)/mililitro'),
(143,'µg/m2','microgramo(s)/metro cuadrado'),
(144,'µkat','microkatal'),
(145,'µkat','microkatales'),
(146,'µl','microlitro(s)'),
(147,'µl/ml','microlitro(s)/mililitro'),
(148,'µmol','micromol(es)'),
(149,'µmol/l','micromol(es)/litro'),
(150,'µmol/ml','micromol(es)/mililitro'),
(151,'mCi','milicurio(s)'),
(152,'mCi/g','milicurio(s)/gramo'),
(153,'mCi/kg','milicurio(s)/kilogramo'),
(154,'mCi/l','milicurio(s)/litro'),
(155,'mCi/µg','milicurio(s)/microgramo'),
(156,'mCi/µl','milicurio(s)/microlitro'),
(157,'mCi/mg','milicurio(s)/miligramo'),
(158,'mCi/ml','milicurio(s)/mililitro'),
(159,'mEq','miliequivalente(s)'),
(160,'mEq/g','miliequivalente(s)/gramo'),
(161,'mEq/kg','miliequivalente(s)/kilogramo'),
(162,'mEq/l','miliequivalente(s)/litro'),
(163,'mEq/µg','miliequivalente(s)/microgramo'),
(164,'mEq/µl','miliequivalente(s)/microlitro'),
(165,'mEq/mg','miliequivalente(s)/miligramo'),
(166,'mEq/ml','miliequivalente(s)/mililitro'),
(167,'mtiter)',''),
(168,'mg','miligramo(s)'),
(169,'mg/m3','miligramo(s)/metro cúbico'),
(170,'mg/g','miligramo(s)/gramo'),
(171,'mg/kg','miligramo(s)/kilogramo'),
(172,'mg/l','miligramo(s)/litro'),
(173,'mg/ml','miligramo(s)/mililitro'),
(174,'mg/m2','miligramo(s)/metro cuadrado'),
(175,'mkatal','milikatal'),
(176,'ml','mililitro(s)'),
(177,'ml/cm2','mililitro(s)/centímetro cuadrado'),
(178,'mm','milimetro'),
(179,'mmol','milimol(es)'),
(180,'mmol/g','milimol(es)/gramo'),
(181,'mmol/kg','milimol(es)/kilogramo'),
(182,'mmol/l','milimol(es)/litro'),
(183,'mmol/ml','milimol(es)/mililitro'),
(184,'millon UFC','millones de unidades formadoras de colonias'),
(185,'millon UFC/g','millones de unidades formadoras de colonias/gramo'),
(186,'millon UFC/ml','millones de unidades formadoras de colonias/mililitro'),
(187,'millon UI','millones de unidadades internacionales'),
(188,'millon de organismos','millon de organismos'),
(189,'millon de organismos/g','millon de organismos/gramo'),
(190,'millon de organismos/mg','millon de organismos/miligramo'),
(191,'millon de organismos/ml','millon de organismos/mililitro'),
(192,'millon de unidades USP','millon de unidades de la Farmacopea de los Estados Udos'),
(193,'millon de unidades','millon de unidades'),
(194,'mOsm/kg','miliosmol(es)/kilogramo'),
(195,'min','minuto'),
(196,'mol','mol(es)'),
(197,'mol/g','mol(es)/gramo'),
(198,'mol/kg','mol(es)/kilogramo'),
(199,'mol/l','mol(es)/litro'),
(200,'mol/mg','mol(es)/miligramo'),
(201,'mol/ml','mol(es)/mililitro'),
(202,'nCi','nanocurio(s)'),
(203,'ng','nanogramo(s)'),
(204,'nkat','nanokatal'),
(205,'nl','nanolitro(s)'),
(206,'nmol','nanomol(es)'),
(207,'nmol/ml','nanomol(es)/mililitro'),
(208,'N','newton'),
(209,'unidades NIH/cm2','NIH unidades de trombina inactivada/centímetro cuadrado'),
(210,'?','ohmio'),
(211,'OZ','onza'),
(212,'PPM','parte por millon'),
(213,'PPM','pascal'),
(214,'%','porcentaje'),
(215,'% (v/v)','porcentaje volumen/volumen'),
(216,'% (p/v)','porcentaje peso/volumen'),
(217,'% (p/p)','porcentaje peso/peso'),
(218,'pg','picogramo(s)'),
(219,'pkat','picokatal'),
(220,'PFU','unidades formadoras de placa'),
(221,'PFU e. 1000 LD50 en ratón','unidad formadora de placa equivalente a 1000 DL50 en ratón'),
(222,'PFU/dosis','unidades formadoras de placa/dosis'),
(223,'PFU/ml','unidades formadoras de placa/mililitro'),
(224,'unidad formadora de viruela','unidad(es) formadoras de viruela'),
(225,'LB','libra'),
(226,'unidades deesión/ml','unidades de presión/mililitro'),
(227,'PNU/ml','unidades de nitrogeno proteico/mililitro'),
(228,'QS','cantidad suficiente'),
(229,'r/min','revoluciones/minuto'),
(230,'s','segundos'),
(231,'S','siemens'),
(232,'Sv','sievert'),
(233,'cm2','centímetro cuadrado'),
(234,'m2','metro cuadrado'),
(235,'T','tesla'),
(236,'miles CFU','miles de unidades formadoras de colonia'),
(237,'miles CFU/g','miles de unidades formadoras de colonia/gramo'),
(238,'miles CFU/ml','miles de unidades formadoras de colonia/mililitro'),
(239,'miles de organismos','miles de organismos'),
(240,'miles de organismos/g','miles de organismos/gramo'),
(241,'miles de organismos/ml','miles de organismos/mililitro'),
(242,'TCID50/dosis','dosis infecciosa de cultivo tisular 50/ dosis'),
(243,'titre','titre'),
(244,'t','tonelada'),
(245,'unidad de tuberculina','unidad(es) de tuberculina'),
(246,'unidad de tuberculina/ml','unidad(es) de tuberculina/mililitro'),
(247,'U','unidades'),
(248,'U/g','unidades/gramo'),
(249,'U/ml','unidades/mililitro'),
(250,'unidades USP','unidades de la Farmacopea de los Estados Unidos'),
(251,'V','voltio'),
(252,'W','vatio'),
(253,'Wb','weber'),
(254,'vp','Particulas Virales'),
(255,'DLmin','Dosis letal mma'),
(256,'DMN','Dosis minima necrotizante'),
(257,'vg','Genomas vectoriales'),
(9000,'Dosis','Dosis'),
(9001,'TPU','TPU'),
(9002,'TSU','TSU'),
(9003,'DBU','DBU'),
(9004,'SU','SU'),
(9005,'IR','IR'),
(9006,'DPP','DPP'),
(9007,'HEP','HEP'),
(9008,'UT','UT'),
(9009,'SQ','SQ'),
(9010,'UB','UB'),
(9011,'DL50','Dosis letal 50'),
(9012,'AU','Unidades de Alergia'),
(9013,'BAU','Bioequivalente Unidades de Alergia'),
(9014,'PNU','Unidades de nitrogeno proteico'),
(9015,'DPU','Unidades de diagnostico no estandarizadas biologicamente')
ON CONFLICT ("code") DO NOTHING;

-- Reapuntar measurement_unit de las tablas evento: de measurement_units (dispensación) a scientific_units.
ALTER TABLE "tvmed_evento" DROP CONSTRAINT "tvmed_evento_measurement_unit_fkey";
ALTER TABLE "tvins_evento" DROP CONSTRAINT "tvins_evento_measurement_unit_fkey";

ALTER TABLE "tvmed_evento" ADD CONSTRAINT "tvmed_evento_measurement_unit_fkey" FOREIGN KEY ("measurement_unit") REFERENCES "scientific_units"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tvins_evento" ADD CONSTRAINT "tvins_evento_measurement_unit_fkey" FOREIGN KEY ("measurement_unit") REFERENCES "scientific_units"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
